fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "andres.alvear01@epn.edu.ec"
    sender_name: "Andres Alvear"
  registration:
    confirmation:
      enabled: true